### PR TITLE
Review comments and changes - Chapter 2

### PR DESCRIPTION
**Pull request by srihari-sridharan**

### CODE REVIEW

**Comment by lucasfcosta** [comment]
Hi @srihari-sridharan, please have a look at the email I've sent you and the development editor in regards to this PR.

Thank you very much ✨

**Comment by srihari-sridharan** [comment]
Thanks @lucasfcosta. 😊

**Comment by srihari-sridharan** [comment]
@lucasfcosta have you sent the email, I have not received it yet. Thanks.

**Comment by lucasfcosta** [comment]
Hi @srihari-sridharan, I've resent my emails this week.

I'd prefer if we'd follow this conversation via email instead of adding commits here. 

Thanks for the work, but I'll close this for now as I think we'd actually be more productive discussing on other mediums.

**Comment by srihari-sridharan** [comment]
@lucasfcosta I closed this PR as it had mostly suggested changes and not fixes.

**Pull request closed without merging**
